
Airport.destroy_all
Amenity.destroy_all
Restaurant.destroy_all
Store.destroy_all

Airport.create(name: "London Heathrow International", code: "LHR", city: "London", country: "United Kingdom", likes: 0, image: "https://www.cityam.com/wp-content/uploads/2020/02/London_Tower_Bridge_City.jpg")
Airport.create(name: "Seattle-Tacoma International", code: "SEA", city: "Seattle", country: "United States", likes: 0, image: "https://www.langan.com/wp-content/uploads/2020/01/Seattle-996x554-1.jpg")
Airport.create(name: "Hartsfield–Jackson Atlanta International", code: "ATL", city: "Atlanta", country: "United States",likes: 0, image: "https://lp-cms-production.imgix.net/2019-06/bee09d1bbbe1a156e0aaadfe76614bad-atlanta.jpg?auto=compress&fit=crop&fm=auto&sharp=10&vib=20&w=1200")
Airport.create(name: "Paris Charles de Gaulle/Roissy", code: "CDG", city: "Paris", country: "France",likes: 0, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRi5XLZogbwkQFZxrQI6z2tjQMoGSQo3-4O1A&usqp=CAU" )
Airport.create(name: "Dallas-Fort Worth International", code: "DFW", city: "Dallas-Fort Worth", country: "United States",likes: 0, image: "https://www.fodors.com/assets/destinations/55/skyline-dallas-texas-usa_980x650.jpg" )
Airport.create(name: "Reykjavík–Keflavík", code: "KEF", city: "Reykjavik", country: "Iceland",likes: 0, image: "https://cdn.britannica.com/71/73371-050-9DFAEC1E/Reykjavik-Iceland.jpg")
Airport.create(name: "Sydney Kingsford Smith", code: "SYD", city: "Sydney", country: "Australia",likes: 0, image: "https://www.nationalgeographic.com/content/dam/travel/Guide-Pages/australia-oceania/sydney-travel.jpg")
Airport.create(name: "Rome–Fiumicino International", code: "FCO", city: "Rome" , country: "Italy",likes: 0, image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7l3X5DJOP4M8tY3mp8CN6RblCVy4XKAtCrQ&usqp=CAU")
Airport.create(name: "Hong Kong International", code: "HKG", city: "Hong Kong", country: "Hong Kong" ,likes: 0, image: "https://media.timeout.com/images/103812417/630/472/image.jpg")
Airport.create(name: "Chicago O'Hare International", code: "ORD", city: "Chicago", country: "United States",likes: 0, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQW8W1akvXFC6c6Z7A0DSas3HPAsX0Xwxq5Fw&usqp=CAU")
Airport.create(name: "Tokyo-Narita International", code: "NRT", city: "Tokyo", country: "Japan",likes: 0, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxe0W46SQG-rVei6yoZluW59D66q7hHMzwNA&usqp=CAU")
Airport.create(name: "Los Angeles International", code: "LAX", city: "Los Angeles", country: "United States",likes: 0, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRES0YcSu1jN3uXYLTgNI6ql5o0-xLRoO-55A&usqp=CAU")
Airport.create(name: "Berlin Brandenburg International", code: "BER", city: "Berlin", country: "Germany",likes: 0, image: "https://a.storyblok.com/f/89778/1168x728/793d02880b/de_00_ber_1.jpeg")
Airport.create(name: "Bangkok Suvarnabhumi", code: "BKK", city: "Bangkok", country: "Thailand",likes: 0, image: "https://bkkaruncloud.b-cdn.net/wp-content/uploads/2016/04/fun-facts-about-bangkok.jpg")
Airport.create(name: "Cancun International", code: "CUN", city: "Cancun", country: "Mexico",likes: 0, image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/11/c7/d1/39/club-med-cancun-yucatan.jpg?w=900&h=-1&s=1")
Airport.create(name: "Toronto Pearson International", code: "YYZ", city: "Toronto", country: "Canada",likes: 0, image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/14/10/2f/e4/toronto.jpg?w=1100&h=600&s=1")

Amenity.create(name: "Free WiFi", service: "Internet", likes: 0, image: "https://image.shutterstock.com/image-vector/wifi-icon-black-wi-fi-260nw-654893110.jpg")
Amenity.create(name: "Water Fountain", service: "Water Fountain", likes: 0, image: "https://static.thenounproject.com/png/29-200.png")
Amenity.create(name: "Prayer Room", service: "Prayer Room", likes: 0, image: "https://cdn3.iconfinder.com/data/icons/accomodation-outline/59/008_-_Prayer_Room-512.png")
Amenity.create(name: "Massage Chairs", service: "Massage Chairs", likes: 0, image: "https://cdn2.vectorstock.com/i/1000x1000/93/51/massage-chair-icon-on-white-background-vector-18149351.jpg")
Amenity.create(name: "Gender Neutral WC", service: "Bathrooms", likes: 0, image: "https://static.thenounproject.com/png/13777-200.png")
Amenity.create(name: "Therapy Dogs", service: "Pets", likes: 0, image: "https://static.thenounproject.com/png/61386-200.png")
Amenity.create(name: "Currency Exchange", service: "Finance", likes: 0, image: "https://image.flaticon.com/icons/png/512/71/71123.png")
Amenity.create(name: "Smoking Room", service: "Smoking", likes: 0, image: "https://cdn4.iconfinder.com/data/icons/car-services-36-icons/110/Car_servicess-32-512.png")
Amenity.create(name: "Outlets", service: "Electronics", likes: 0, image: "https://cdn3.iconfinder.com/data/icons/wpzoom-developer-icon-set/500/125-512.png")
Amenity.create(name: "Trolleys", service: "Baggage Services", likes: 0, image: "https://static.thenounproject.com/png/1138102-200.png")


AirportAmenity.create(airport_id: 1, amenity_id: 1)
AirportAmenity.create(airport_id: 1, amenity_id: 2)
AirportAmenity.create(airport_id: 1, amenity_id: 3)
AirportAmenity.create(airport_id: 1, amenity_id: 7)
AirportAmenity.create(airport_id: 1, amenity_id: 8)
AirportAmenity.create(airport_id: 1, amenity_id: 9)
AirportAmenity.create(airport_id: 1, amenity_id: 10)
AirportAmenity.create(airport_id: 2, amenity_id: 1)
AirportAmenity.create(airport_id: 2, amenity_id: 2)
AirportAmenity.create(airport_id: 2, amenity_id: 3)
AirportAmenity.create(airport_id: 2, amenity_id: 4)
AirportAmenity.create(airport_id: 2, amenity_id: 5)
AirportAmenity.create(airport_id: 2, amenity_id: 7)
AirportAmenity.create(airport_id: 2, amenity_id: 9)
AirportAmenity.create(airport_id: 2, amenity_id: 10)

AirportAmenity.create(airport_id: 3, amenity_id: 1)
AirportAmenity.create(airport_id: 3, amenity_id: 2)
AirportAmenity.create(airport_id: 3, amenity_id: 4)
AirportAmenity.create(airport_id: 3, amenity_id: 5)
AirportAmenity.create(airport_id: 3, amenity_id: 6)
AirportAmenity.create(airport_id: 3, amenity_id: 9)
AirportAmenity.create(airport_id: 3, amenity_id: 10)
AirportAmenity.create(airport_id: 4, amenity_id: 1)
AirportAmenity.create(airport_id: 4, amenity_id: 2)
AirportAmenity.create(airport_id: 4, amenity_id: 3)
AirportAmenity.create(airport_id: 4, amenity_id: 4)
AirportAmenity.create(airport_id: 4, amenity_id: 5)
AirportAmenity.create(airport_id: 4, amenity_id: 7)
AirportAmenity.create(airport_id: 4, amenity_id: 9)
AirportAmenity.create(airport_id: 4, amenity_id: 10)

AirportAmenity.create(airport_id: 5, amenity_id: 1)
AirportAmenity.create(airport_id: 5, amenity_id: 2)
AirportAmenity.create(airport_id: 5, amenity_id: 4)
AirportAmenity.create(airport_id: 5, amenity_id: 5)
AirportAmenity.create(airport_id: 5, amenity_id: 6)
AirportAmenity.create(airport_id: 5, amenity_id: 9)
AirportAmenity.create(airport_id: 5, amenity_id: 10)
AirportAmenity.create(airport_id: 6, amenity_id: 1)
AirportAmenity.create(airport_id: 6, amenity_id: 2)
AirportAmenity.create(airport_id: 6, amenity_id: 4)
AirportAmenity.create(airport_id: 6, amenity_id: 5)
AirportAmenity.create(airport_id: 6, amenity_id: 7)
AirportAmenity.create(airport_id: 6, amenity_id: 9)
AirportAmenity.create(airport_id: 6, amenity_id: 10)

AirportAmenity.create(airport_id: 7, amenity_id: 1)
AirportAmenity.create(airport_id: 7, amenity_id: 2)
AirportAmenity.create(airport_id: 7, amenity_id: 4)
AirportAmenity.create(airport_id: 7, amenity_id: 5)
AirportAmenity.create(airport_id: 7, amenity_id: 7)
AirportAmenity.create(airport_id: 7, amenity_id: 9)
AirportAmenity.create(airport_id: 7, amenity_id: 10)
AirportAmenity.create(airport_id: 8, amenity_id: 1)
AirportAmenity.create(airport_id: 8, amenity_id: 2)
AirportAmenity.create(airport_id: 8, amenity_id: 4)
AirportAmenity.create(airport_id: 8, amenity_id: 5)
AirportAmenity.create(airport_id: 8, amenity_id: 7)
AirportAmenity.create(airport_id: 8, amenity_id: 8)
AirportAmenity.create(airport_id: 8, amenity_id: 9)
AirportAmenity.create(airport_id: 8, amenity_id: 10)

AirportAmenity.create(airport_id: 9, amenity_id: 1)
AirportAmenity.create(airport_id: 9, amenity_id: 2)
AirportAmenity.create(airport_id: 9, amenity_id: 3)
AirportAmenity.create(airport_id: 9, amenity_id: 4)
AirportAmenity.create(airport_id: 9, amenity_id: 5)
AirportAmenity.create(airport_id: 9, amenity_id: 6)
AirportAmenity.create(airport_id: 9, amenity_id: 7)
AirportAmenity.create(airport_id: 9, amenity_id: 8)
AirportAmenity.create(airport_id: 9, amenity_id: 9)
AirportAmenity.create(airport_id: 9, amenity_id: 10)
AirportAmenity.create(airport_id: 10, amenity_id: 1)
AirportAmenity.create(airport_id: 10, amenity_id: 2)
AirportAmenity.create(airport_id: 10, amenity_id: 4)
AirportAmenity.create(airport_id: 10, amenity_id: 5)
AirportAmenity.create(airport_id: 10, amenity_id: 6)
AirportAmenity.create(airport_id: 10, amenity_id: 9)
AirportAmenity.create(airport_id: 10, amenity_id: 10)

AirportAmenity.create(airport_id: 11, amenity_id: 1)
AirportAmenity.create(airport_id: 11, amenity_id: 2)
AirportAmenity.create(airport_id: 11, amenity_id: 3)
AirportAmenity.create(airport_id: 11, amenity_id: 4)
AirportAmenity.create(airport_id: 11, amenity_id: 5)
AirportAmenity.create(airport_id: 11, amenity_id: 6)
AirportAmenity.create(airport_id: 11, amenity_id: 7)
AirportAmenity.create(airport_id: 11, amenity_id: 8)
AirportAmenity.create(airport_id: 11, amenity_id: 9)
AirportAmenity.create(airport_id: 11, amenity_id: 10)
AirportAmenity.create(airport_id: 12, amenity_id: 1)
AirportAmenity.create(airport_id: 12, amenity_id: 2)
AirportAmenity.create(airport_id: 12, amenity_id: 4)
AirportAmenity.create(airport_id: 12, amenity_id: 5)
AirportAmenity.create(airport_id: 12, amenity_id: 6)
AirportAmenity.create(airport_id: 12, amenity_id: 9)
AirportAmenity.create(airport_id: 12, amenity_id: 10)

AirportAmenity.create(airport_id: 13, amenity_id: 1)
AirportAmenity.create(airport_id: 13, amenity_id: 2)
AirportAmenity.create(airport_id: 13, amenity_id: 4)
AirportAmenity.create(airport_id: 13, amenity_id: 5)
AirportAmenity.create(airport_id: 13, amenity_id: 7)
AirportAmenity.create(airport_id: 13, amenity_id: 9)
AirportAmenity.create(airport_id: 13, amenity_id: 10)
AirportAmenity.create(airport_id: 14, amenity_id: 1)
AirportAmenity.create(airport_id: 14, amenity_id: 2)
AirportAmenity.create(airport_id: 14, amenity_id: 3)
AirportAmenity.create(airport_id: 14, amenity_id: 4)
AirportAmenity.create(airport_id: 14, amenity_id: 5)
AirportAmenity.create(airport_id: 14, amenity_id: 6)
AirportAmenity.create(airport_id: 14, amenity_id: 8)
AirportAmenity.create(airport_id: 14, amenity_id: 9)
AirportAmenity.create(airport_id: 14, amenity_id: 10)

AirportAmenity.create(airport_id: 15, amenity_id: 1)
AirportAmenity.create(airport_id: 15, amenity_id: 2)
AirportAmenity.create(airport_id: 15, amenity_id: 4)
AirportAmenity.create(airport_id: 15, amenity_id: 5)
AirportAmenity.create(airport_id: 15, amenity_id: 6)
AirportAmenity.create(airport_id: 15, amenity_id: 8)
AirportAmenity.create(airport_id: 15, amenity_id: 9)
AirportAmenity.create(airport_id: 15, amenity_id: 10)
AirportAmenity.create(airport_id: 16, amenity_id: 1)
AirportAmenity.create(airport_id: 16, amenity_id: 2)
AirportAmenity.create(airport_id: 16, amenity_id: 4)
AirportAmenity.create(airport_id: 16, amenity_id: 5)
AirportAmenity.create(airport_id: 16, amenity_id: 6)
AirportAmenity.create(airport_id: 16, amenity_id: 9)
AirportAmenity.create(airport_id: 16, amenity_id: 10)



Restaurant.create(airport_id: 1, name: "McDonalds", cost: "$", cuisine: "American", typeof: "Fastfood", likes: 0, image: "https://logo-logos.com/wp-content/uploads/2016/10/McDonalds_logo_logotype.png")
Restaurant.create(airport_id: 2, name: "McDonalds", cost: "$", cuisine: "American", typeof: "Fastfood", likes: 0, image: "https://logo-logos.com/wp-content/uploads/2016/10/McDonalds_logo_logotype.png")
Restaurant.create(airport_id: 3, name: "McDonalds", cost: "$", cuisine: "American", typeof: "Fastfood", likes: 0, image: "https://logo-logos.com/wp-content/uploads/2016/10/McDonalds_logo_logotype.png")
Restaurant.create(airport_id: 4, name: "McDonalds", cost: "$", cuisine: "American", typeof: "Fastfood", likes: 0, image: "https://logo-logos.com/wp-content/uploads/2016/10/McDonalds_logo_logotype.png")
Restaurant.create(airport_id: 5, name: "McDonalds", cost: "$", cuisine: "American", typeof: "Fastfood", likes: 0, image: "https://logo-logos.com/wp-content/uploads/2016/10/McDonalds_logo_logotype.png")
Restaurant.create(airport_id: 6, name: "McDonalds", cost: "$", cuisine: "American", typeof: "Fastfood", likes: 0, image: "https://logo-logos.com/wp-content/uploads/2016/10/McDonalds_logo_logotype.png")
Restaurant.create(airport_id: 7, name: "McDonalds", cost: "$", cuisine: "American", typeof: "Fastfood", likes: 0, image: "https://logo-logos.com/wp-content/uploads/2016/10/McDonalds_logo_logotype.png")
Restaurant.create(airport_id: 8, name: "McDonalds", cost: "$", cuisine: "American", typeof: "Fastfood", likes: 0, image: "https://logo-logos.com/wp-content/uploads/2016/10/McDonalds_logo_logotype.png")
Restaurant.create(airport_id: 9, name: "McDonalds", cost: "$", cuisine: "American", typeof: "Fastfood", likes: 0, image: "https://logo-logos.com/wp-content/uploads/2016/10/McDonalds_logo_logotype.png")
Restaurant.create(airport_id: 10, name: "McDonalds", cost: "$", cuisine: "American", typeof: "Fastfood", likes: 0, image: "https://logo-logos.com/wp-content/uploads/2016/10/McDonalds_logo_logotype.png")
Restaurant.create(airport_id: 11, name: "McDonalds", cost: "$", cuisine: "American", typeof: "Fastfood", likes: 0, image: "https://logo-logos.com/wp-content/uploads/2016/10/McDonalds_logo_logotype.png")
Restaurant.create(airport_id: 12, name: "McDonalds", cost: "$", cuisine: "American", typeof: "Fastfood", likes: 0, image: "https://logo-logos.com/wp-content/uploads/2016/10/McDonalds_logo_logotype.png")
Restaurant.create(airport_id: 13, name: "McDonalds", cost: "$", cuisine: "American", typeof: "Fastfood", likes: 0, image: "https://logo-logos.com/wp-content/uploads/2016/10/McDonalds_logo_logotype.png")
Restaurant.create(airport_id: 14, name: "McDonalds", cost: "$", cuisine: "American", typeof: "Fastfood", likes: 0, image: "https://logo-logos.com/wp-content/uploads/2016/10/McDonalds_logo_logotype.png")
Restaurant.create(airport_id: 15, name: "McDonalds", cost: "$", cuisine: "American", typeof: "Fastfood", likes: 0, image: "https://logo-logos.com/wp-content/uploads/2016/10/McDonalds_logo_logotype.png")
Restaurant.create(airport_id: 16, name: "McDonalds", cost: "$", cuisine: "American", typeof: "Fastfood", likes: 0, image: "https://logo-logos.com/wp-content/uploads/2016/10/McDonalds_logo_logotype.png")
Restaurant.create(airport_id: 1, name: "Starbucks", cost: "$", cuisine: "Coffee", typeof: "Fastfood", likes: 0, image: "https://upload.wikimedia.org/wikipedia/en/thumb/d/d3/Starbucks_Corporation_Logo_2011.svg/1200px-Starbucks_Corporation_Logo_2011.svg.png")
Restaurant.create(airport_id: 2, name: "Starbucks", cost: "$", cuisine: "Coffee", typeof: "Fastfood", likes: 0, image: "https://upload.wikimedia.org/wikipedia/en/thumb/d/d3/Starbucks_Corporation_Logo_2011.svg/1200px-Starbucks_Corporation_Logo_2011.svg.png")
Restaurant.create(airport_id: 3, name: "Starbucks", cost: "$", cuisine: "Coffee", typeof: "Fastfood", likes: 0, image: "https://upload.wikimedia.org/wikipedia/en/thumb/d/d3/Starbucks_Corporation_Logo_2011.svg/1200px-Starbucks_Corporation_Logo_2011.svg.png")
Restaurant.create(airport_id: 4, name: "Starbucks", cost: "$", cuisine: "Coffee", typeof: "Fastfood", likes: 0, image: "https://upload.wikimedia.org/wikipedia/en/thumb/d/d3/Starbucks_Corporation_Logo_2011.svg/1200px-Starbucks_Corporation_Logo_2011.svg.png")
Restaurant.create(airport_id: 5, name: "Starbucks", cost: "$", cuisine: "Coffee", typeof: "Fastfood", likes: 0, image: "https://upload.wikimedia.org/wikipedia/en/thumb/d/d3/Starbucks_Corporation_Logo_2011.svg/1200px-Starbucks_Corporation_Logo_2011.svg.png")
Restaurant.create(airport_id: 6, name: "Starbucks", cost: "$", cuisine: "Coffee", typeof: "Fastfood", likes: 0, image: "https://upload.wikimedia.org/wikipedia/en/thumb/d/d3/Starbucks_Corporation_Logo_2011.svg/1200px-Starbucks_Corporation_Logo_2011.svg.png")
Restaurant.create(airport_id: 7, name: "Starbucks", cost: "$", cuisine: "Coffee", typeof: "Fastfood", likes: 0, image: "https://upload.wikimedia.org/wikipedia/en/thumb/d/d3/Starbucks_Corporation_Logo_2011.svg/1200px-Starbucks_Corporation_Logo_2011.svg.png")
Restaurant.create(airport_id: 8, name: "Starbucks", cost: "$", cuisine: "Coffee", typeof: "Fastfood", likes: 0, image: "https://upload.wikimedia.org/wikipedia/en/thumb/d/d3/Starbucks_Corporation_Logo_2011.svg/1200px-Starbucks_Corporation_Logo_2011.svg.png")
Restaurant.create(airport_id: 9, name: "Starbucks", cost: "$", cuisine: "Coffee", typeof: "Fastfood", likes: 0, image: "https://upload.wikimedia.org/wikipedia/en/thumb/d/d3/Starbucks_Corporation_Logo_2011.svg/1200px-Starbucks_Corporation_Logo_2011.svg.png")
Restaurant.create(airport_id: 10, name: "Starbucks", cost: "$", cuisine: "Coffee", typeof: "Fastfood", likes: 0, image: "https://upload.wikimedia.org/wikipedia/en/thumb/d/d3/Starbucks_Corporation_Logo_2011.svg/1200px-Starbucks_Corporation_Logo_2011.svg.png")
Restaurant.create(airport_id: 11, name: "Starbucks", cost: "$", cuisine: "Coffee", typeof: "Fastfood", likes: 0, image: "https://upload.wikimedia.org/wikipedia/en/thumb/d/d3/Starbucks_Corporation_Logo_2011.svg/1200px-Starbucks_Corporation_Logo_2011.svg.png")
Restaurant.create(airport_id: 12, name: "Starbucks", cost: "$", cuisine: "Coffee", typeof: "Fastfood", likes: 0, image: "https://upload.wikimedia.org/wikipedia/en/thumb/d/d3/Starbucks_Corporation_Logo_2011.svg/1200px-Starbucks_Corporation_Logo_2011.svg.png")
Restaurant.create(airport_id: 13, name: "Starbucks", cost: "$", cuisine: "Coffee", typeof: "Fastfood", likes: 0, image: "https://upload.wikimedia.org/wikipedia/en/thumb/d/d3/Starbucks_Corporation_Logo_2011.svg/1200px-Starbucks_Corporation_Logo_2011.svg.png")
Restaurant.create(airport_id: 14, name: "Starbucks", cost: "$", cuisine: "Coffee", typeof: "Fastfood", likes: 0, image: "https://upload.wikimedia.org/wikipedia/en/thumb/d/d3/Starbucks_Corporation_Logo_2011.svg/1200px-Starbucks_Corporation_Logo_2011.svg.png")
Restaurant.create(airport_id: 15, name: "Starbucks", cost: "$", cuisine: "Coffee", typeof: "Fastfood", likes: 0, image: "https://upload.wikimedia.org/wikipedia/en/thumb/d/d3/Starbucks_Corporation_Logo_2011.svg/1200px-Starbucks_Corporation_Logo_2011.svg.png")
Restaurant.create(airport_id: 16, name: "Starbucks", cost: "$", cuisine: "Coffee", typeof: "Fastfood", likes: 0, image: "https://upload.wikimedia.org/wikipedia/en/thumb/d/d3/Starbucks_Corporation_Logo_2011.svg/1200px-Starbucks_Corporation_Logo_2011.svg.png")

Restaurant.create(airport_id: 12, name: "Caffè Nero", cost: "$", cuisine: "Coffee", typeof: "Fastfood", likes: 0, image: "https://www.pinclipart.com/picdir/middle/63-630515_caffe-nero-have-appointed-oxford-air-conditioning-as.png")
Restaurant.create(airport_id: 14, name: "Caffè Nero", cost: "$", cuisine: "Coffee", typeof: "Fastfood", likes: 0, image: "https://www.pinclipart.com/picdir/middle/63-630515_caffe-nero-have-appointed-oxford-air-conditioning-as.png")
Restaurant.create(airport_id: 8, name: "Caffè Nero", cost: "$", cuisine: "Coffee", typeof: "Fastfood", likes: 0, image: "https://www.pinclipart.com/picdir/middle/63-630515_caffe-nero-have-appointed-oxford-air-conditioning-as.png")
Restaurant.create(airport_id: 1, name: "Pret A Manger", cost: "$", cuisine: "Sandwiches", typeof: "Fastfood", likes: 0, image: "https://logos-download.com/wp-content/uploads/2016/04/Pret_a_Manger_logo_logotype.jpg")
Restaurant.create(airport_id: 4, name: "Pret A Manger", cost: "$", cuisine: "Sandwiches", typeof: "Fastfood", likes: 0, image: "https://logos-download.com/wp-content/uploads/2016/04/Pret_a_Manger_logo_logotype.jpg")
Restaurant.create(airport_id: 6, name: "Pret A Manger", cost: "$", cuisine: "Sandwiches", typeof: "Fastfood", likes: 0, image: "https://logos-download.com/wp-content/uploads/2016/04/Pret_a_Manger_logo_logotype.jpg")
Restaurant.create(airport_id: 8, name: "Pret A Manger", cost: "$", cuisine: "Sandwiches", typeof: "Fastfood", likes: 0, image: "https://logos-download.com/wp-content/uploads/2016/04/Pret_a_Manger_logo_logotype.jpg")
Restaurant.create(airport_id: 13, name: "Pret A Manger", cost: "$", cuisine: "Sandwiches", typeof: "Fastfood", likes: 0, image: "https://logos-download.com/wp-content/uploads/2016/04/Pret_a_Manger_logo_logotype.jpg")
Restaurant.create(airport_id: 11, name: "Pret A Manger", cost: "$", cuisine: "Sandwiches", typeof: "Fastfood", likes: 0, image: "https://logos-download.com/wp-content/uploads/2016/04/Pret_a_Manger_logo_logotype.jpg")

Restaurant.create(airport_id: 1, name: "Costa", cost: "$", cuisine: "Coffee", typeof: "Fastfood", likes: 0, image: "https://upload.wikimedia.org/wikipedia/en/thumb/4/42/CostaLogo.svg/1200px-CostaLogo.svg.png")
Restaurant.create(airport_id: 4, name: "Costa", cost: "$", cuisine: "Coffee", typeof: "Fastfood", likes: 0, image: "https://upload.wikimedia.org/wikipedia/en/thumb/4/42/CostaLogo.svg/1200px-CostaLogo.svg.png")
Restaurant.create(airport_id: 6, name: "Costa", cost: "$", cuisine: "Coffee", typeof: "Fastfood", likes: 0, image: "https://upload.wikimedia.org/wikipedia/en/thumb/4/42/CostaLogo.svg/1200px-CostaLogo.svg.png")
Restaurant.create(airport_id: 8, name: "Costa", cost: "$", cuisine: "Coffee", typeof: "Fastfood", likes: 0, image: "https://upload.wikimedia.org/wikipedia/en/thumb/4/42/CostaLogo.svg/1200px-CostaLogo.svg.png")

Restaurant.create(airport_id: 2, name: "Peet's Coffee", cost: "$", cuisine: "Coffee", typeof: "Fastfood", likes: 0, image: "https://offers.collegebacker.com/wp-content/uploads/2020/04/peets_logo_180x180.png")
Restaurant.create(airport_id: 3, name: "Peet's Coffee", cost: "$", cuisine: "Coffee", typeof: "Fastfood", likes: 0, image: "https://offers.collegebacker.com/wp-content/uploads/2020/04/peets_logo_180x180.png")
Restaurant.create(airport_id: 5, name: "Peet's Coffee", cost: "$", cuisine: "Coffee", typeof: "Fastfood", likes: 0, image: "https://offers.collegebacker.com/wp-content/uploads/2020/04/peets_logo_180x180.png")
Restaurant.create(airport_id: 10, name: "Peet's Coffee", cost: "$", cuisine: "Coffee", typeof: "Fastfood", likes: 0, image: "https://offers.collegebacker.com/wp-content/uploads/2020/04/peets_logo_180x180.png")
Restaurant.create(airport_id: 12, name: "Peet's Coffee", cost: "$", cuisine: "Coffee", typeof: "Fastfood", likes: 0, image: "https://offers.collegebacker.com/wp-content/uploads/2020/04/peets_logo_180x180.png")

Restaurant.create(airport_id: 4, name: "Ladurée", cost: "$$", cuisine: "Bakery", typeof: "Takeaway", likes: 0, image: "https://deltafonts.com/wp-content/uploads/Laduree.png")
Restaurant.create(airport_id: 1, name: "Ladurée", cost: "$$", cuisine: "Bakery", typeof: "Takeaway", likes: 0, image: "https://deltafonts.com/wp-content/uploads/Laduree.png")
Restaurant.create(airport_id: 8, name: "Ladurée", cost: "$$", cuisine: "Bakery", typeof: "Takeaway", likes: 0, image: "https://deltafonts.com/wp-content/uploads/Laduree.png")
Restaurant.create(airport_id: 9, name: "Ladurée", cost: "$$", cuisine: "Bakery", typeof: "Takeaway", likes: 0, image: "https://deltafonts.com/wp-content/uploads/Laduree.png")

Restaurant.create(airport_id: 4, name: "Miso Kitchen", cost: "$$", cuisine: "Japanese", typeof: "Eat-in", likes: 0, image: "https://www.narita-airport.jp/img/original/3650")
Restaurant.create(airport_id: 11, name: "Miso Kitchen", cost: "$$", cuisine: "Japanese", typeof: "Eat-in", likes: 0, image: "https://www.narita-airport.jp/img/original/3650")

Restaurant.create(airport_id: 11, name: "T's Tantan", cost: "$$", cuisine: "Japanese", typeof: "Eat-in", likes: 0, image: "https://www.narita-airport.jp/img/original/24301")

Restaurant.create(airport_id: 1, name: "Yo Sushi", cost: "$$", cuisine: "Japanese", typeof: "Fast Casual", likes: 0, image: "https://res.cloudinary.com/westfielddg/image/upload/westfield-media/uk/retailer/logos/djqmk0pfgn1x3rkpsx0h.png")

Restaurant.create(airport_id: 2, name: "Evergreen's", cost: "$", cuisine: "American", typeof: "Fast Casual", likes: 0, image: "https://ubb8m2c7z7g1ei2ee1isdrqd-wpengine.netdna-ssl.com/wp-content/uploads/2020/10/Evergreens-Transparent.svg")
Restaurant.create(airport_id: 2, name: "Poke to the Max", cost: "$$", cuisine: "Hawaiian", typeof: "Fast Casual", likes: 0, image: "https://ubb8m2c7z7g1ei2ee1isdrqd-wpengine.netdna-ssl.com/wp-content/uploads/2020/11/Poke-to-the-Max-logo.svg")
Restaurant.create(airport_id: 2, name: "La Pisa Cafe", cost: "$$", cuisine: "Italian", typeof: "Fast Casual", likes: 0, image: "https://ubb8m2c7z7g1ei2ee1isdrqd-wpengine.netdna-ssl.com/wp-content/uploads/2020/11/La-Pisa-LOGO4c.svg")
Restaurant.create(airport_id: 2, name: "Hachi-ko", cost: "$$", cuisine: "Japanese", typeof: "Fast Casual", likes: 0, image: "https://ubb8m2c7z7g1ei2ee1isdrqd-wpengine.netdna-ssl.com/wp-content/uploads/2020/10/Hachi-ko-LOGO-4cH.svg")
Restaurant.create(airport_id: 2, name: "Capitol Hill Food Hall", cost: "$$", cuisine: "Seafood", typeof: "Fast Casual", likes: 0, image: "https://ubb8m2c7z7g1ei2ee1isdrqd-wpengine.netdna-ssl.com/wp-content/uploads/2020/10/CapitolHillLogo_Seal.svg")

Restaurant.create(airport_id: 3, name: "Beerhive", cost: "$$", cuisine: "American", typeof: "Bar", likes: 0, image: "https://i1.wp.com/doctorale.com/wp-content/uploads/2016/01/Duvel-glass.jpg")
Restaurant.create(airport_id: 16, name: "Beerhive", cost: "$$", cuisine: "American", typeof: "Bar", likes: 0, image: "https://i1.wp.com/doctorale.com/wp-content/uploads/2016/01/Duvel-glass.jpg")
Restaurant.create(airport_id: 5, name: "Beerhive", cost: "$$", cuisine: "American", typeof: "Bar", likes: 0, image: "https://i1.wp.com/doctorale.com/wp-content/uploads/2016/01/Duvel-glass.jpg")
Restaurant.create(airport_id: 7, name: "Beerhive", cost: "$$", cuisine: "American", typeof: "Bar", likes: 0, image: "https://i1.wp.com/doctorale.com/wp-content/uploads/2016/01/Duvel-glass.jpg")

Restaurant.create(airport_id: 9, name: "Yung Kee", cost: "$$$", cuisine: "Cantonese", typeof: "Eat-in", likes: 0, image: "https://www.hongkongairport.com/iwov-resources/image/shop-dine/dining/yung-kee-logo.png")
Restaurant.create(airport_id: 9, name: "KaravanStop", cost: "$", cuisine: "Coffee", typeof: "Fastfood", likes: 0, image: "https://www.hongkongairport.com/iwov-resources/image/shop-dine/dining/karavanstop-logo.jpg")
Restaurant.create(airport_id: 9, name: "Moon Thai Express", cost: "$", cuisine: "Thai", typeof: "Fast casual", likes: 0, image: "https://www.hongkongairport.com/iwov-resources/image/shop-dine/dining/moon-thai-logo.png")
Restaurant.create(airport_id: 9, name: "Crystal Jade", cost: "$$$", cuisine: "Shanghainese", typeof: "Eat-in", likes: 0, image: "https://www.hongkongairport.com/iwov-resources/image/shop-dine/dining/crystal-jade-logo.png")
Restaurant.create(airport_id: 9, name: "Caviar House", cost: "$$$", cuisine: "French", typeof: "Eat-in", likes: 0, image: "https://www.hongkongairport.com/iwov-resources/image/shop-dine/dining/caviar-logo.png")
Restaurant.create(airport_id: 1, name: "Caviar House", cost: "$$$", cuisine: "French", typeof: "Eat-in", likes: 0, image: "https://www.hongkongairport.com/iwov-resources/image/shop-dine/dining/caviar-logo.png")
Restaurant.create(airport_id: 4, name: "Caviar House", cost: "$$$", cuisine: "French", typeof: "Eat-in", likes: 0, image: "https://www.hongkongairport.com/iwov-resources/image/shop-dine/dining/caviar-logo.png")
Restaurant.create(airport_id: 6, name: "Caviar House", cost: "$$$", cuisine: "French", typeof: "Eat-in", likes: 0, image: "https://www.hongkongairport.com/iwov-resources/image/shop-dine/dining/caviar-logo.png")


Restaurant.create(airport_id: 10, name: "Pinkberry", cost: "$", cuisine: "Frozen Yogurt", typeof: "Takeaway", likes: 0, image: "https://res.cloudinary.com/grubhub/image/upload/d_search:browse-images:default.jpg/w_auto,h_168,c_pad,fl_lossy,f_auto/alcjt2boklkmcsw0scmj")
Restaurant.create(airport_id: 12, name: "Pinkberry", cost: "$", cuisine: "Frozen Yogurt", typeof: "Takeaway", likes: 0, image: "https://res.cloudinary.com/grubhub/image/upload/d_search:browse-images:default.jpg/w_auto,h_168,c_pad,fl_lossy,f_auto/alcjt2boklkmcsw0scmj")
Restaurant.create(airport_id: 3, name: "Pinkberry", cost: "$", cuisine: "Frozen Yogurt", typeof: "Takeaway", likes: 0, image: "https://res.cloudinary.com/grubhub/image/upload/d_search:browse-images:default.jpg/w_auto,h_168,c_pad,fl_lossy,f_auto/alcjt2boklkmcsw0scmj")

Store.create(airport_id: 1, name: "Boots", cost: "$", category: "Drugstore", likes: 0, image: "https://www.ogilvy.ie/wp-content/uploads/2019/05/logo-boots.png")
Store.create(airport_id: 1, name: "Sunglasses Hut", cost: "$$$", category: "Apparel", likes: 0, image: "https://d1yjjnpx0p53s8.cloudfront.net/styles/logo-thumbnail/s3/0002/3105/brand.gif?itok=fZZt-IgB")
Store.create(airport_id: 1, name: "World of Whiskies", cost: "$$", category: "Alcohol", likes: 0, image: "https://cdn.technologynetworks.com/tn/images/thumbs/jpeg/640_360/whiskey-the-target-of-fraud-327900.jpg?v=10560096")
Store.create(airport_id: 4, name: "Hermès", cost: "$$$$$$$$$", category: "Luxury Apparel & Accessories", likes: 0, image: "https://www.parisaeroport.fr/images/default-source/passager-images/boutiques/enseignes/hermes.jpg")
Store.create(airport_id: 4, name: "Bvlgari", cost: "$$$", category: "Jewelery & Luxury Accessories", likes: 0, image: "https://www.moodiedavittreport.com/wp-content/uploads/2017/11/Unknown.jpeg")
Store.create(airport_id: 4, name: "Louis Vuitton", cost: "$$$", category: "Luxury Apparel & Accessories", likes: 0, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7r6CTf5OIjvRzapf5JYb734QMi57P-tFYLg&usqp=CAU")
Store.create(airport_id: 4, name: "Chanel", cost: "$$$", category: "Luxury Apparel & Accessories", likes: 0, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRWWNmHV7bnEEeyYVoFPakBPIIRRk3DLHnaA&usqp=CAU")
Store.create(airport_id: 5, name: "3Sixty Duty Free", cost: "$", category: "Souvenir", likes: 0, image: "https://www.dfwairport.com/apps/cma/images/345x194/21100_0.png")
Store.create(airport_id: 5, name: "7-Eleven", cost: "$", category: "Convenience Store", likes: 0, image: "https://theapopkavoice.com/wp-content/uploads/2020/02/20180806161134-GettyImages-992242738-edit.jpeg")
Store.create(airport_id: 5, name: "InMotion Entertainment", cost: "$$", category: "Electronic", likes: 0, image: "https://www.dfwairport.com/apps/cma/images/345x194/201_0.png")
Store.create(airport_id: 5, name: "Montblanc", cost: "$$$", category: "High-end Accessories", likes: 0, image: "https://i.pinimg.com/originals/4f/bb/a9/4fbba9de7a56803969749b7dafeaa8b4.jpg")
Store.create(airport_id: 6, name: "Blue Lagoon", cost: "$$", category: "Cosmetics", likes: 0, image: "https://images.ctfassets.net/w65k7w0nsb8q/2wTQxbFJiuFmUCktZeNgWH/b59d2cfb7fec7bed46f42094fe133d41/SPA-1.jpg")
Store.create(airport_id: 6, name: "Duty Free Iceland", cost: "$", category: "Souvenir", likes: 0, image: "https://www.businessdestinations.com/wp-content/uploads/2014/11/Keflavik-Duty-Free.jpg")
Store.create(airport_id: 6, name: "66° NORTH", cost: "$$", category: "Apparel", likes: 0, image: "https://www.travelociraptor.com/wp-content/uploads/2018/02/airport11.jpg")
Store.create(airport_id: 6, name: "Penninn Eymundsson", cost: "$$", category: "Books & Magazines", likes: 0, image: "https://www.vb.is/media/cache/82/4d/824d375a75e432642cb9da8601580a38.jpg")


